runtime: java21
instance_class: F2
entrypoint: 'java -jar ktor-sample-all.jar'

inbound_services:
  - warmup

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 500ms
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.6

# Network settings
network:
  session_affinity: true

# Environment variables (customize as needed)
env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=512m"
  JDBC_DATABASE_URL: "jdbc:postgresql://[INSTANCE_CONNECTION_NAME]/timetable_db"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "2004"

# Request handlers
handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /.*
    script: auto
    secure: always

# Health check configuration
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# VPC Access Connector (uncomment if needed)
# vpc_access_connector:
#   name: projects/YOUR_PROJECT_ID/locations/YOUR_REGION/connectors/YOUR_CONNECTOR

# Resources
resources:
  cpu: 1
  memory_gb: 1.0
  disk_size_gb: 10
